version: '3.8'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    volumes:
      - "C:/volumes/localstack:/var/lib/localstack"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/var/lib/localstack  # Ensure data is written here
    restart: always